[package]
name = "kansa-app"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "kansa desktop app"

[lib]
name = "kansa_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
kansa-core = { path = "../../crates/kansa-core" }
tauri = { version = "2", features = [] }
serde_json.workspace = true
