//! `export --format reqtrace` (spec §4.2, `out~groups~1`, `obj~req-revs~1`).
//!
//! Writes `requirements.yaml` (every rev of every requirement, `groups:` titles added) and
//! `not-in-scope.yaml` (retired requirements with their reason as `justification`), plus a
//! minimal `.reqtrace.toml` if none exists so `reqtrace validate` lints both files.

use crate::model::{now, ExportRecord, Pattern, Rating, Status};
use crate::store::Store;
use anyhow::{Context, Result};
use serde::Serialize;
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};

#[derive(Debug, Serialize)]
struct Item<'a> {
    id: String,
    statement: &'a str,
    #[serde(skip_serializing_if = "Option::is_none")]
    pattern: Option<Pattern>,
    status: Status,
    #[serde(skip_serializing_if = "Option::is_none")]
    rating: Option<Rating>,
    #[serde(skip_serializing_if = "Option::is_none")]
    owner: Option<&'a str>,
    #[serde(skip_serializing_if = "Option::is_none")]
    reason: Option<&'a str>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    groups: Vec<String>,
}

#[derive(Debug, Serialize)]
struct Exception {
    id: String,
    justification: String,
}

#[derive(Debug, Clone)]
pub struct ExportResult {
    pub inventory: PathBuf,
    pub exceptions: PathBuf,
    pub items: usize,
    pub exception_count: usize,
    pub inventory_hash: String,
}

/// Render the inventory YAML (deterministic: sorted by slug, then rev).
pub fn render_inventory(store: &Store) -> Result<(String, usize)> {
    let groups = store.groups_by_req()?;
    let mut files = store.all_reqs()?;
    files.sort_by(|a, b| {
        a.first()
            .map(|r| &r.id.slug)
            .cmp(&b.first().map(|r| &r.id.slug))
    });
    let mut items = vec![];
    for revs in &files {
        for r in revs {
            items.push(Item {
                id: r.id.to_string(),
                statement: &r.statement,
                pattern: r.pattern,
                status: r.status,
                rating: r.rating,
                owner: r.owner.as_deref(),
                reason: r.reason.as_deref(),
                groups: groups.get(&r.id.key()).cloned().unwrap_or_default(),
            });
        }
    }
    let n = items.len();
    let mut s = String::from(
        "# Generated by kansa — do not edit. Every rev of every requirement; groups are titles.\n",
    );
    if items.is_empty() {
        s.push_str("[]\n");
    } else {
        s.push_str(&serde_yaml::to_string(&items)?);
    }
    Ok((s, n))
}

pub fn render_exceptions(store: &Store) -> Result<(String, usize)> {
    let mut ex = vec![];
    for r in store.current_reqs()? {
        if r.status == Status::Retired {
            ex.push(Exception {
                id: r.id.to_string(),
                justification: r.reason.clone().unwrap_or_else(|| "retired".into()),
            });
        }
    }
    ex.sort_by(|a, b| a.id.cmp(&b.id));
    let n = ex.len();
    let mut s =
        String::from("# Generated by kansa — retired requirements with their retire reason.\n");
    if ex.is_empty() {
        s.push_str("[]\n");
    } else {
        s.push_str(&serde_yaml::to_string(&ex)?);
    }
    Ok((s, n))
}

pub fn inventory_hash(store: &Store) -> Result<String> {
    let (s, _) = render_inventory(store)?;
    Ok(hex::encode(Sha256::digest(s.as_bytes())))
}

/// Write both files into `out_dir` and record the export in the store.
pub fn export_reqtrace(store: &Store, out_dir: &Path) -> Result<ExportResult> {
    std::fs::create_dir_all(out_dir).with_context(|| format!("creating {}", out_dir.display()))?;
    let (inv, items) = render_inventory(store)?;
    let (exc, exception_count) = render_exceptions(store)?;
    let inventory = out_dir.join("requirements.yaml");
    let exceptions = out_dir.join("not-in-scope.yaml");
    store.write_atomic(&inventory, inv.as_bytes())?;
    store.write_atomic(&exceptions, exc.as_bytes())?;
    let cfg = out_dir.join(".reqtrace.toml");
    if !cfg.exists() {
        store.write_atomic(
            &cfg,
            b"[scan]\nglobs = [\"**/*.md\"]\nexceptions = \"not-in-scope.yaml\"\n",
        )?;
    }
    let inventory_hash = hex::encode(Sha256::digest(inv.as_bytes()));
    store.save_last_export(&ExportRecord {
        at: now(),
        out_dir: out_dir.to_string_lossy().replace('\\', "/"),
        inventory_hash: inventory_hash.clone(),
    })?;
    Ok(ExportResult {
        inventory,
        exceptions,
        items,
        exception_count,
        inventory_hash,
    })
}

/// Has anything changed since the last export?
pub fn has_unexported_changes(store: &Store) -> Result<bool> {
    match store.last_export()? {
        None => Ok(store.all_reqs()?.iter().any(|f| !f.is_empty())),
        Some(rec) => Ok(rec.inventory_hash != inventory_hash(store)?),
    }
}

/// Locate a `reqtrace` binary: `$REQTRACE_BIN`, else on PATH.
pub fn find_reqtrace() -> Option<PathBuf> {
    if let Ok(p) = std::env::var("REQTRACE_BIN") {
        let p = PathBuf::from(p);
        if p.exists() {
            return Some(p);
        }
    }
    let exe = if cfg!(windows) {
        "reqtrace.exe"
    } else {
        "reqtrace"
    };
    std::env::var_os("PATH").and_then(|paths| {
        std::env::split_paths(&paths)
            .map(|d| d.join(exe))
            .find(|p| p.is_file())
    })
}

/// Run `reqtrace validate` on an export; returns (exit code, combined output).
pub fn run_reqtrace_validate(bin: &Path, out_dir: &Path) -> Result<(i32, String)> {
    let out = crate::proc::command(bin)
        .arg("validate")
        .arg("--inventory")
        .arg("requirements.yaml")
        .arg("--config")
        .arg(".reqtrace.toml")
        .current_dir(out_dir)
        .output()
        .with_context(|| format!("running {}", bin.display()))?;
    let mut text = String::from_utf8_lossy(&out.stdout).into_owned();
    text.push_str(&String::from_utf8_lossy(&out.stderr));
    Ok((out.status.code().unwrap_or(-1), text))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::id::Id;
    use crate::model::*;

    fn seeded() -> (tempfile::TempDir, Store) {
        let dir = tempfile::tempdir().unwrap();
        let cfg = RepoConfig {
            github: "o/n".into(),
            remote: "r".into(),
            default_branch: "main".into(),
            local_path: "x".into(),
            tracked: vec![],
            registered_at: now(),
            last_fetch: None,
        };
        let s = Store::init(&dir.path().join("store"), &cfg).unwrap();
        let mk = |id: &str, st: Status| {
            let mut r = ReqRev::new(
                id.parse::<Id>().unwrap(),
                format!("Statement for {id}."),
                "t",
            );
            r.status = st;
            r
        };
        let mut a1 = mk("req~login-throttling~1", Status::Confirmed);
        a1.rating = Some(Rating {
            value: Level::H,
            risk: Level::M,
        });
        let a2 = mk("req~login-throttling~2", Status::Confirmed);
        s.save_req_revs("login-throttling", &[a1, a2]).unwrap();
        let mut old = mk("req~old-captcha~1", Status::Retired);
        old.reason = Some("Superseded by risk-based challenges.".into());
        s.save_req_revs("old-captcha", &[old]).unwrap();
        s.save_req_revs("audit-log", &[mk("req~audit-log~1", Status::Extracted)])
            .unwrap();
        s.save_grp_revs(
            "auth",
            &[Group {
                id: "grp~auth~1".parse().unwrap(),
                title: "Auth".into(),
                description: None,
                members: vec!["req~login-throttling~2".parse().unwrap()],
                history: vec![],
            }],
        )
        .unwrap();
        (dir, s)
    }

    #[test]
    fn export_writes_both_files_and_records() {
        let (dir, s) = seeded();
        let out = dir.path().join("out");
        assert!(has_unexported_changes(&s).unwrap());
        let r = export_reqtrace(&s, &out).unwrap();
        assert_eq!(r.items, 4);
        assert_eq!(r.exception_count, 1);
        let inv = std::fs::read_to_string(&r.inventory).unwrap();
        assert!(inv.contains("id: req~login-throttling~1"));
        assert!(inv.contains("id: req~login-throttling~2"));
        assert!(inv.contains("groups:\n  - Auth"));
        assert!(inv.contains("rating:\n  - H\n  - M"));
        let exc = std::fs::read_to_string(&r.exceptions).unwrap();
        assert!(exc.contains("id: req~old-captcha~1"));
        assert!(exc.contains("justification: Superseded"));
        assert!(!has_unexported_changes(&s).unwrap());
        // deterministic
        let r2 = export_reqtrace(&s, &out).unwrap();
        assert_eq!(r.inventory_hash, r2.inventory_hash);
    }

    #[test]
    fn export_passes_reqtrace_validate() {
        let Some(bin) = find_reqtrace() else {
            eprintln!("SKIP: reqtrace binary not found (set REQTRACE_BIN or add to PATH)");
            return;
        };
        let (dir, s) = seeded();
        let out = dir.path().join("out");
        export_reqtrace(&s, &out).unwrap();
        let (code, text) = run_reqtrace_validate(&bin, &out).unwrap();
        assert_eq!(code, 0, "reqtrace validate failed:\n{text}");
        assert!(text.contains("inventory OK: 4 items"), "{text}");
        assert!(text.contains("exceptions OK: 1 entry"), "{text}");
    }
}
